services:
  client:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./backend
    ports:
      - "5000:4000"
    depends_on:
      - db
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: root
      DB_PASSWORD: password
      PORT: 4000
      NODE_ENV: development

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: